# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 23:11
# from __future__ import unicode_literals

import os
import logging

from django.conf import settings
from django.db import migrations

from incomewealth.utils import read_csv, update_or_create_income_and_wealth

logger = logging.getLogger(__name__)


def load_initial_data(apps, schema_editor):
    csv_dump_file_path = os.path.join(
        settings.BASE_DIR, settings.INIT_CSV_DUMP_FILE_REL_PATH)

    with open(csv_dump_file_path) as f:
        data = read_csv(f)
        update_or_create_income_and_wealth(data)
        logger.info('DONE.')


def truncate_table(apps, schema_editor):
    IncomeWealth = apps.get_model('app', 'IncomeWealth')
    IncomeWealth.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_code=truncate_table)
    ]
