# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 23:11
# from __future__ import unicode_literals

import os
import csv
import logging

from django.conf import settings
from django.db import migrations

logger = logging.getLogger(__name__)


def load_initial_data(apps, schema_editor):
    IncomeWealth = apps.get_model('app', 'IncomeWealth')

    csv_dump_file_path = os.path.join(
        settings.BASE_DIR, settings.INITIAL_DB_DUMP_FILE_RELATIVE_PATH)

    with open(csv_dump_file_path) as f:
        reader = csv.reader(f, delimiter=';')
        for index, row in enumerate(reader):
            # index 0 contains column names
            if index == 0:
                continue

            year = int(row[0])

            obj, created = IncomeWealth.objects.update_or_create(
                year=year,
                defaults={
                    'income_top_10': float(row[1]),
                    'wealth_top_10': float(row[2]),
                    'income_bottom_50': float(row[3]),
                    'wealth_bottom_50': float(row[4]),
                })

            logger.info('{}, year: {}'.format(
                'INSERTED' if created else 'UPDATED', year))


def truncate_table(apps, schema_editor):
    IncomeWealth = apps.get_model('app', 'IncomeWealth')
    IncomeWealth.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_code=truncate_table)
    ]
