version: '2'
services:

  # db:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-db
  #   volumes:
  #     - /var/lib/mysql    
  #   environment:
  #     MYSQL_ROOT_PASSWORD: supersecure

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "80:80"
    # links:
    #   - db
    # depends_on:
    #   - db
